r"""Correlated Coletto B.7--B.10 bed-film coefficient oracle.

Gate 1g must not vary the external heat coefficient ``h_Q`` and binary-film
coefficient ``h_M`` as independent Cartesian coordinates.  In the locally
available DT source model they are generated by one hydrodynamic/property
state through

``Nu_eps = 0.6941 Re_eps**0.579 Pr**(1/3)``,

``h_Q = Nu_eps k_g alpha_L / (2 R alpha_V)``, and

``h_M = h_Q/(rho_g cp_g) (Pr/Sc)**(2/3)``.

This module preserves that covariance and the exact spherical area basis.  It
does not qualify the source's Reynolds convention, the bulk binary
diffusivity, or a soybean water/n-hexane film coefficient.  Every result is
therefore a provenance-bearing, non-qualifying numerical oracle.

D20, 2026-09-23 (owner ruling "I rule D19 and D20 as recommended"; packet
``docs/GT_PS2_RULING_PACKET_D20_VOIDAGE_REYNOLDS_2026-09-22.md`` option 1;
build record ``docs/GT_PS2_D20_LEVEL0_BUILD_RECORD_2026-09-23.md``): both
the prefactor and the Reynolds definition are now the primary source's own.
Faner (2008) PhD thesis, printed page 106 Equation 4.23,
``Re_eps = D_EE rho_g v_g / [mu_g (1 - eps)]`` -- the SOLID fraction -- and
printed page 109 Equation 4.27, ``Nu_eps = 0.6941 Re_eps^0.579 Pr^(1/3)``,
R^2 = 0.929, fitted over ``Re_eps`` 18.8 to 275.3 on a sample layer three to
five particle diameters deep.  The digitized source is pinned by
``paper/analysis/datasets/faner2008_thesis_4_5_3/DATASET_RECORD.md``.
UNTIL 2026-09-23 this module divided the Reynolds number by ``eps`` and used
the prefactor 0.6949; at the frozen ``eps = 0.40`` of the project's bed that
returned a film coefficient 1/0.7898 times the one it returns now.
No flux law is inferred here: Packet C still requires a separately qualified
binary-film solver.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field

from dtdc_simulator.core2.particle import surface_active_set as sas


@dataclass(frozen=True)
class PackedBedFilmState:
    """One common state used to generate the complete B.7--B.10 pair."""

    particle_radius_m: float
    bed_void_fraction: float
    gas_density_kg_m3: float
    gas_superficial_velocity_m_s: float
    gas_dynamic_viscosity_pa_s: float
    gas_heat_capacity_j_kg_k: float
    gas_thermal_conductivity_w_m_k: float
    bulk_binary_diffusivity_m2_s: float
    state_provenance: str
    reynolds_convention_provenance: str
    physically_qualifying: bool = field(default=False, init=False)

    def __post_init__(self) -> None:
        positive = (
            self.particle_radius_m,
            self.gas_density_kg_m3,
            self.gas_dynamic_viscosity_pa_s,
            self.gas_heat_capacity_j_kg_k,
            self.gas_thermal_conductivity_w_m_k,
            self.bulk_binary_diffusivity_m2_s,
        )
        if not all(math.isfinite(value) and value > 0.0 for value in positive):
            raise ValueError("bed-film radii and gas properties must be positive and finite")
        if (
            not math.isfinite(self.gas_superficial_velocity_m_s)
            or self.gas_superficial_velocity_m_s < 0.0
        ):
            raise ValueError("superficial velocity must be finite and non-negative")
        if (
            not math.isfinite(self.bed_void_fraction)
            or not 0.0 < self.bed_void_fraction < 1.0
        ):
            raise ValueError("bed void fraction must lie strictly inside (0,1)")
        for name, value in (
            ("state provenance", self.state_provenance),
            ("Reynolds-convention provenance", self.reynolds_convention_provenance),
        ):
            if not isinstance(value, str) or not value.strip():
                raise ValueError(f"{name} must be explicit")

    @property
    def particle_area_per_particle_volume_m2_m3(self) -> float:
        """Exact sphere area ``a_p=3/R``; no bed fraction is included."""

        return 3.0 / self.particle_radius_m

    @property
    def particle_area_per_bed_volume_m2_m3(self) -> float:
        """Exact bed area ``a_b=(1-epsilon_b) 3/R`` applied once."""

        return (1.0 - self.bed_void_fraction) * (
            self.particle_area_per_particle_volume_m2_m3
        )


@dataclass(frozen=True)
class CorrelatedBedFilmPair:
    """One inseparable heat/mass coefficient pair from a common state."""

    state: PackedBedFilmState
    reynolds_voidage: float
    prandtl: float
    schmidt: float
    nusselt_voidage: float
    heat_transfer_w_m2_k: float
    binary_mass_transfer_m_s: float
    correlation_id: str = field(default="COLETTO-B7-B10-CORRELATED-PAIR", init=False)
    physically_qualifying: bool = field(default=False, init=False)

    def __post_init__(self) -> None:
        values = (
            self.reynolds_voidage,
            self.prandtl,
            self.schmidt,
            self.nusselt_voidage,
            self.heat_transfer_w_m2_k,
            self.binary_mass_transfer_m_s,
        )
        if not all(math.isfinite(value) and value >= 0.0 for value in values):
            raise ValueError("correlated bed-film values must be finite and non-negative")
        if self.prandtl <= 0.0 or self.schmidt <= 0.0:
            raise ValueError("Prandtl and Schmidt numbers must be strictly positive")
        if self.state.gas_superficial_velocity_m_s == 0.0:
            if any(
                value != 0.0
                for value in (
                    self.reynolds_voidage,
                    self.nusselt_voidage,
                    self.heat_transfer_w_m2_k,
                    self.binary_mass_transfer_m_s,
                )
            ):
                raise ValueError("the printed B.7 correlation has an exact zero-flow limit")
        elif any(
            value <= 0.0
            for value in (
                self.reynolds_voidage,
                self.nusselt_voidage,
                self.heat_transfer_w_m2_k,
                self.binary_mass_transfer_m_s,
            )
        ):
            raise ValueError("positive flow must produce a strictly positive coefficient pair")

    @property
    def common_provenance(self) -> str:
        return (
            f"{self.correlation_id}; {self.state.state_provenance}; "
            f"{self.state.reynolds_convention_provenance}"
        )

    def as_surface_selections(self) -> sas.SurfaceTransferSelections:
        """Adapt one positive pair to Packet-C provenance containers.

        Degenerate intervals deliberately prevent independent interpolation.
        A zero-flow pair is a limiting oracle and cannot be adapted to the
        strictly-positive Packet-C coefficient container.
        """

        if self.heat_transfer_w_m2_k <= 0.0 or self.binary_mass_transfer_m_s <= 0.0:
            raise ValueError("zero-flow limiting coefficients cannot be selected as a film law")
        film = sas.SurfaceTransferCoefficientInterval(
            kind=sas.TransferCoefficientKind.BINARY_MAXWELL_STEFAN_FILM,
            lower=self.binary_mass_transfer_m_s,
            upper=self.binary_mass_transfer_m_s,
            units="m/s",
            provenance=self.common_provenance,
        ).select(0.0)
        heat = sas.SurfaceTransferCoefficientInterval(
            kind=sas.TransferCoefficientKind.HEAT_TRANSFER,
            lower=self.heat_transfer_w_m2_k,
            upper=self.heat_transfer_w_m2_k,
            units="W/(m^2 K)",
            provenance=self.common_provenance,
        ).select(0.0)
        return sas.SurfaceTransferSelections(binary_film=film, heat_transfer=heat)


def coletto_b7_b10_pair(state: PackedBedFilmState) -> CorrelatedBedFilmPair:
    """Evaluate the printed B.7--B.10 chain without independent retuning."""

    if not isinstance(state, PackedBedFilmState):
        raise TypeError("a packed-bed film state is required")
    eps = state.bed_void_fraction
    alpha_l = 1.0 - eps
    diameter = 2.0 * state.particle_radius_m
    # D20: Equation 4.23 of the source divides by the solid fraction
    # ``alpha_l = 1 - eps`` (printed page 106).  WAS ``* eps``.
    reynolds = (
        state.gas_density_kg_m3
        * state.gas_superficial_velocity_m_s
        * diameter
        / (state.gas_dynamic_viscosity_pa_s * alpha_l)
    )
    prandtl = (
        state.gas_heat_capacity_j_kg_k
        * state.gas_dynamic_viscosity_pa_s
        / state.gas_thermal_conductivity_w_m_k
    )
    schmidt = state.gas_dynamic_viscosity_pa_s / (
        state.gas_density_kg_m3 * state.bulk_binary_diffusivity_m2_s
    )
    # D20: Equation 4.27 of the source, printed page 109.  WAS 0.6949.
    nusselt = 0.6941 * reynolds**0.579 * prandtl ** (1.0 / 3.0)
    heat = (
        nusselt
        * state.gas_thermal_conductivity_w_m_k
        * alpha_l
        / (diameter * eps)
    )
    mass = (
        heat
        / (state.gas_density_kg_m3 * state.gas_heat_capacity_j_kg_k)
        * (prandtl / schmidt) ** (2.0 / 3.0)
    )
    return CorrelatedBedFilmPair(
        state=state,
        reynolds_voidage=reynolds,
        prandtl=prandtl,
        schmidt=schmidt,
        nusselt_voidage=nusselt,
        heat_transfer_w_m2_k=heat,
        binary_mass_transfer_m_s=mass,
    )


__all__ = [
    "CorrelatedBedFilmPair",
    "PackedBedFilmState",
    "coletto_b7_b10_pair",
]
